#name: mcarchvsc
version: "3.8"

services:

  discovery:
    hostname: discovery
    build: ./discovery-service
    ports:
      - 8020:8020
    networks:
      - backend

  user:
    build: ./user-service
    depends_on:
      - discovery
#      - gateway
      - psdb
    networks:
      - backend
    ports:
      - 8082:8082

  psdb:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
    ports:
      - 5433:5432
    restart: always
    volumes:
      - ./db:/var/lib/postgres
    networks:
      - backend

volumes:
  db:

networks:
  backend:
