version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "18424:5672"
      - "18446:15672"
    networks:
      - backend

  discovery:
    image: rsww_184249-discovery
    hostname: discovery
    ports:
      - "18451:8010"
    depends_on:
      - rabbitmq
    networks:
      - backend

  gateway:
    image: rsww_184249-gateway
    ports:
      - "18469:8082"
    depends_on:
      - rabbitmq
      - discovery
    networks:
      - backend


  # custom services
  hotel:
    image: rsww_184249-hotel
    depends_on:
      - rabbitmq
      - discovery
      - gateway
    networks:
      - backend

  offer-provider:
    image: rsww_184249-offer-provider
    depends_on:
      - rabbitmq
      - discovery
      - gateway
    networks:
      - backend

  payment:
    image: rsww_184249-payment
    depends_on:
      - rabbitmq
      - discovery
      - gateway
    networks:
      - backend

  reservation:
    image: rsww_184249-reservation
    depends_on:
      - rabbitmq
      - discovery
      - gateway
    networks:
      - backend

  transport:
    image: rsww_184249-transport
    depends_on:
      - rabbitmq
      - discovery
      - gateway
    networks:
      - backend

  user:
    image: rsww_184249-user
    depends_on:
      - rabbitmq
      - discovery
      - gateway
    networks:
      - backend

  data-generator:
    image: mcarchvsc-data-generator
    depends_on:
      - rabbitmq
      - discovery
      - gateway
      - hotel
      - transport
    networks:
      - backend

networks:
  backend:
