version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "18424:5672"
      - "18446:15672"
    networks:
      - backend

  front:
    image: ghcr.io/microarchitecturovisco/travel-ui:latest
    hostname: front
    ports:
      - "18453:80"
    depends_on:
      - rabbitmq
      - discovery
    networks:
      - backend
    deploy:
      replicas: 2

  discovery:
    image: ghcr.io/microarchitecturovisco/discovery:latest
    hostname: discovery
    ports:
      - "18451:8010"
    depends_on:
      - rabbitmq
    networks:
      - backend

  gateway:
    image: ghcr.io/microarchitecturovisco/gateway:latest
    ports:
      - "18469:8082"
    depends_on:
      - rabbitmq
      - discovery
    networks:
      - backend


  hotel:
    image: ghcr.io/microarchitecturovisco/hotel:latest
    depends_on:
      - rabbitmq
      - discovery
      - gateway
    networks:
      - backend
    deploy:
      replicas: 8

  offer-provider:
    image: ghcr.io/microarchitecturovisco/offer-provider:latest
    depends_on:
      - rabbitmq
      - discovery
      - gateway
    networks:
      - backend
    deploy:
      replicas: 2

  payment:
    image: ghcr.io/microarchitecturovisco/payment:latest
    depends_on:
      - rabbitmq
      - discovery
      - gateway
    networks:
      - backend

  reservation:
    image: ghcr.io/microarchitecturovisco/reservation:latest
    depends_on:
      - rabbitmq
      - discovery
      - gateway
    networks:
      - backend

  transport:
    image: ghcr.io/microarchitecturovisco/transport:latest
    depends_on:
      - rabbitmq
      - discovery
      - gateway
    networks:
      - backend
    deploy:
      replicas: 8

  user:
    image: ghcr.io/microarchitecturovisco/user:latest
    depends_on:
      - rabbitmq
      - discovery
      - gateway
    networks:
      - backend

  data-generator:
    image: ghcr.io/microarchitecturovisco/data-generator:latest
    depends_on:
      - rabbitmq
      - discovery
      - gateway
      - hotel
      - transport
    networks:
      - backend

networks:
  backend:
